server:
  port: 8764

spring:
  application:
    name: bud-zuul

eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
    instance-id: http://192.168.1.168:8764 #服务中心的信息显示（如果IP地址不显示的话，进行配置）
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8771/eureka/

zuul:
  routes:
   bud-common:
     path: /bud-common/**
     serviceId: bud-common
   bud-util:
     path: /bud-util/**
     serviceId: bud-util
