server:
  port: 8760

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: bud-gateway
# 以下路由方式和 java 代码配置方式二选一
#  cloud:
#    gateway:
#      default-filters:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#      - id: bud-feign
#        uri: lb://bud-util/test/feignTest?name=bud-common
#        predicates:
#        - Path=/bud-feign/**
#        filters:
#        - StripPrefix= 1
#      - id: bud-ribbon
#        uri: http://localhost:8763/test/ribbonTest?name=bud-common
#        predicates:
#        - Path=/bud-ribbon/**
#        filters:
#        - StripPrefix= 1


