server:
  port: 8760

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: bud-gateway
  # 以下路由方式和 java 代码配置方式二选一
  cloud:
    gateway:
      default-filters:
      discovery:
        locator:
          enabled: true # gateway开启服务注册和发现，并且为每个服务创建一个router
          lower-case-service-id: true # 请求路径上的服务名配置为小写
      routes:
#      - id: bud-data
#        uri: lb://bud-data/test/feignTest
#        predicates:
#        - Path=/bud-feign/**
#        filters:
#        - StripPrefix= 1
      - id: bud-data
        uri: lb://bud-data/test/ribbonTest
        predicates:
        - Path=/bud-ribbon/**
        filters:
        - StripPrefix= 1
      - id: sys
        uri: lb://bud-sys/sys/login
        predicates:
        - Path=/sys/login
        filters:
        - StripPrefix= 1

auth:
  skip:
    urls: /sys/login,/bud-data
#    - /bud-data
    # 有效时长 单位：d:天、h:小时、m:分钟、s:秒
    effective-time: 1h

# token黑名单 存储key
jwt:
  blacklist:
    key:
      format: JWT_BLACKLIST::%s
  secret:
    key: kunan01
